import { createContext, useContext, useState, useCallback } from "react";

const LanguageContext = createContext(null);
export const useLanguage = () => useContext(LanguageContext);

const translations = {
  pt: {
    // Login
    "login.subtitle": "Motor de Decisão",
    "login.name": "Nome",
    "login.name_placeholder": "Seu nome",
    "login.email": "Email",
    "login.password": "Senha",
    "login.submit_register": "Criar Conta",
    "login.submit_login": "Entrar",
    "login.toggle_register": "Não tem conta? Criar",
    "login.toggle_login": "Já tem conta? Entrar",
    "login.success_register": "Conta criada!",
    "login.success_login": "Bem-vindo de volta!",
    "login.error": "Erro ao autenticar",

    // Dashboard
    "dash.title": "Suas Análises",
    "dash.subtitle": "Motor de decisão para anúncios",
    "dash.new_analysis": "Nova Análise",
    "dash.first_analysis": "Criar Primeira Análise",
    "dash.empty_question": "Qual decisão você precisa tomar hoje?",
    "dash.empty_desc": "Descreva seu produto e deixe o motor decidir o melhor anúncio.",
    "dash.history": "Histórico",
    "dash.new_product": "+ Novo produto",
    "dash.deleted": "Análise excluída",
    "dash.delete_error": "Erro ao excluir",
    "dash.open": "Abrir",
    "dash.delete": "Excluir",
    "dash.logout": "Sair",
    "dash.versions_generated": "versões geradas",

    // Live Panel
    "panel.active_product": "Produto Ativo",
    "panel.product": "Produto",
    "panel.current_strategy": "Estratégia Atual",
    "panel.biggest_weakness": "Maior Fraqueza",
    "panel.next_action": "Próxima Ação Recomendada",
    "panel.improve_ad": "Melhorar anúncio",
    "panel.compare_market": "Comparar com mercado",
    "panel.analyze_competitor": "Analisar concorrente",

    // Radar
    "radar.title": "Radar de Tendências",
    "radar.subtitle": "Briefing semanal do nicho",
    "radar.generate": "Gerar Radar",
    "radar.generating": "Gerando radar...",
    "radar.empty": "Gere um radar para ver tendências do seu nicho",
    "radar.last_update": "Última atualização",
    "radar.changes": "Mudanças no Mercado",
    "radar.patterns": "Padrões Emergentes",
    "radar.recommendations": "Recomendações",
    "radar.summary": "Resumo",

    // Status
    "status.created": "Criado",
    "status.parsed": "Analisado",
    "status.generated": "Anúncios Gerados",
    "status.simulated": "Simulado",
    "status.completed": "Concluído",

    // Analysis Flow
    "flow.step1": "Descreva o Produto",
    "flow.step2": "Interpretação Estratégica",
    "flow.step3": "Variações de Anúncios",
    "flow.step4": "Simulação de Público",
    "flow.step5": "Resultado Final",
    "flow.step1_desc": "Preencha os dados do produto para iniciar a análise.",
    "flow.step2_desc": "O sistema interpretou estrategicamente seu produto.",
    "flow.step3_desc": "3 variações de anúncios foram geradas automaticamente.",
    "flow.step4_desc": "4 perfis de público simulados reagiram aos anúncios.",
    "flow.step5_desc": "O motor de decisão escolheu o melhor anúncio.",
    "flow.back": "Voltar",
    "flow.quick": "Rápido",
    "flow.complete": "Completo",
    "flow.fill_example": "Gerar exemplo",
    "flow.product_name": "Nome do Produto",
    "flow.niche": "Nicho",
    "flow.main_promise": "Promessa Principal",
    "flow.audience": "Público-Alvo",
    "flow.benefits": "Benefícios",
    "flow.mechanism": "Ingredientes / Mecanismo",
    "flow.tone": "Tom Desejado",
    "flow.optional": "(opcional)",
    "flow.compliance_risk": "Risco de bloqueio detectado",
    "flow.compliance_safe": "Evite promessas médicas absolutas. O sistema vai sinalizar risco de bloqueio.",
    "flow.time_estimate": "Leva ~45s para análise completa",
    "flow.submit": "Encontrar o melhor anúncio",
    "flow.generate_ads": "Escolher o anúncio vencedor",
    "flow.run_simulation": "Rodar simulação",
    "flow.run_decision": "Rodar motor de decisão",
    "flow.refine": "Refinar dados do produto",
    "flow.refine_desc": "Adicione benefícios, mecanismo e tom para resultados mais precisos",
    "flow.additional_data": "Dados Adicionais",
    "flow.close": "Fechar",
    "flow.example_filled": "Exemplo preenchido!",
    "flow.error_create": "Erro ao criar análise",
    "flow.error_generate": "Erro ao gerar anúncios",
    "flow.error_simulate": "Erro ao simular público",
    "flow.error_decide": "Erro ao processar decisão",

    // Strategy
    "strategy.title": "Interpretação Estratégica",
    "strategy.consciousness": "Nível de Consciência",
    "strategy.angle": "Ângulo de Venda",
    "strategy.pain": "Dor Central",
    "strategy.big_idea": "Big Idea",
    "strategy.mechanism": "Mecanismo Percebido",
    "strategy.objections": "Objeções Prováveis",
    "strategy.compliance_score": "Compliance Score",

    // Ads
    "ads.experiment": "Experimento de Clique",
    "ads.hypothesis": "Hipótese",
    "ads.works_for": "Funciona melhor para",
    "ads.hook": "Hook",
    "ads.copy": "Copy",
    "ads.ugc_script": "Roteiro UGC",
    "ads.strengths": "Pontos fortes",
    "ads.weaknesses": "Pontos fracos",
    "ads.ctr": "CTR Est.",
    "ads.curiosity": "Curiosidade",
    "ads.block_risk": "Risco Bloqueio",
    "ads.conversion": "Conversão",
    "ads.experimental_note": "Não avaliamos anúncios por estética, e sim por reação provável do público.",

    // Simulation
    "sim.ad_num": "Anúncio",
    "sim.first_reaction": "1ª reação",
    "sim.after_2s": "Após 2s",
    "sim.would_click": "Clicaria se",
    "sim.trend": "Tendência geral",
    "sim.conflict": "Conflito",

    // Decision
    "dec.verdict": "Veredito do Motor de Decisão",
    "dec.chosen": "Anúncio Escolhido: Variação",
    "dec.score": "Pontuação",
    "dec.wrong_choice": "Consequência de escolher errado",
    "dec.use_now": "Este é o anúncio que você deve usar agora",
    "dec.investment": "Se estivesse investindo R$2.000",
    "dec.next_step": "Próximo passo recomendado",
    "dec.reason": "Motivo",
    "dec.weaknesses_detected": "Fraquezas detectadas",
    "dec.improvement_suggestion": "Sugestão de melhoria",
    "dec.lp_structure": "Estrutura de LP sugerida",
    "dec.compatible_audience": "Público mais compatível",
    "dec.ranking": "Ranking",
    "dec.loop_msg": "O sistema continuará aprendendo se você gerar novas versões.",
    "dec.use_ad": "Usar este anúncio",
    "dec.improve": "Melhorar anúncio",
    "dec.new_variation": "Testar nova variação",
    "dec.next_tests": "Próximos testes recomendados",
    "dec.copied": "Copiado!",
    "dec.share_copied": "Link público copiado!",
    "dec.share_error": "Erro ao gerar link",
    "dec.improve_error": "Erro ao criar melhoria",

    // Competitor
    "comp.title": "Analisar Concorrente",
    "comp.headline": "Decodifique a estratégia",
    "comp.desc": "Cole a URL de um anúncio ou landing page do concorrente.",
    "comp.analyze": "Analisar",
    "comp.extraction": "Extração Estratégica",
    "comp.opening_type": "Tipo de Abertura",
    "comp.promise": "Promessa",
    "comp.mechanism": "Mecanismo",
    "comp.proof": "Prova",
    "comp.cta": "CTA",
    "comp.psychology": "Psicologia",
    "comp.visual_format": "Formato Visual",
    "comp.block_risk": "Risco de Bloqueio",
    "comp.what_it_does": "O que o anúncio tenta fazer",
    "comp.why_works": "Por que pode funcionar",
    "comp.where_weak": "Onde perde força",
    "comp.how_beat": "Como superar",
    "comp.keywords": "Palavras-chave",
    "comp.ctas_found": "CTAs encontrados",
    "comp.create_superior": "CRIAR VERSÃO SUPERIOR",
    "comp.history": "Análises anteriores",
    "comp.show": "Mostrar",
    "comp.hide": "Ocultar",
    "comp.done": "Análise concluída!",
    "comp.error": "Erro ao analisar URL",

    // Market
    "mkt.title": "Comparar com Mercado",
    "mkt.desc_prefix": "Veja como o mercado vende no nicho",
    "mkt.desc_suffix": "e onde você tem vantagem.",
    "mkt.scan_info": "O motor vai analisar como o mercado vende no nicho",
    "mkt.scan_detail": "Vai identificar padrões dominantes, anúncios persistentes e comparar com sua estratégia.",
    "mkt.scan": "Escanear mercado",
    "mkt.rescan": "Escanear novamente",
    "mkt.hooks": "Distribuição de Hooks no Mercado",
    "mkt.patterns": "Padrões Dominantes",
    "mkt.persistent": "Anúncios Persistentes",
    "mkt.examples": "Exemplos do Mercado",
    "mkt.persistence": "Persistência",
    "mkt.vs_market": "Sua Estratégia vs Mercado",
    "mkt.how_market": "Como o mercado vende",
    "mkt.where_differ": "Onde você difere",
    "mkt.advantage": "Sua Vantagem Competitiva",
    "mkt.generic_risk": "Risco de parecer genérico",
    "mkt.recommendation": "Recomendação Prática",
    "mkt.generate_creative": "GERAR CRIATIVO BASEADO NA VANTAGEM",
    "mkt.done": "Comparação concluída!",
    "mkt.error": "Erro ao comparar com mercado",

    // Stepper
    "step.product": "Produto",
    "step.strategy": "Estratégia",
    "step.ads": "Anúncios",
    "step.simulation": "Simulação",
    "step.decision": "Decisão",

    // Hook types
    "hook.pergunta": "Pergunta",
    "hook.historia": "História",
    "hook.lista": "Lista",
    "hook.prova_social": "Prova Social",
    "hook.mecanismo": "Mecanismo",
    "hook.choque": "Choque",
  },

  en: {
    "login.subtitle": "Decision Engine",
    "login.name": "Name",
    "login.name_placeholder": "Your name",
    "login.email": "Email",
    "login.password": "Password",
    "login.submit_register": "Create Account",
    "login.submit_login": "Sign In",
    "login.toggle_register": "Don't have an account? Sign Up",
    "login.toggle_login": "Already have an account? Sign In",
    "login.success_register": "Account created!",
    "login.success_login": "Welcome back!",
    "login.error": "Authentication error",

    "dash.title": "Your Analyses",
    "dash.subtitle": "Ad decision engine",
    "dash.new_analysis": "New Analysis",
    "dash.first_analysis": "Create First Analysis",
    "dash.empty_question": "What decision do you need to make today?",
    "dash.empty_desc": "Describe your product and let the engine decide the best ad.",
    "dash.history": "History",
    "dash.new_product": "+ New product",
    "dash.deleted": "Analysis deleted",
    "dash.delete_error": "Error deleting",
    "dash.open": "Open",
    "dash.delete": "Delete",
    "dash.logout": "Logout",
    "dash.versions_generated": "versions generated",

    "panel.active_product": "Active Product",
    "panel.product": "Product",
    "panel.current_strategy": "Current Strategy",
    "panel.biggest_weakness": "Biggest Weakness",
    "panel.next_action": "Recommended Next Action",
    "panel.improve_ad": "Improve ad",
    "panel.compare_market": "Compare with market",
    "panel.analyze_competitor": "Analyze competitor",

    "radar.title": "Trend Radar",
    "radar.subtitle": "Weekly niche briefing",
    "radar.generate": "Generate Radar",
    "radar.generating": "Generating radar...",
    "radar.empty": "Generate a radar to see trends in your niche",
    "radar.last_update": "Last update",
    "radar.changes": "Market Changes",
    "radar.patterns": "Emerging Patterns",
    "radar.recommendations": "Recommendations",
    "radar.summary": "Summary",

    "status.created": "Created",
    "status.parsed": "Analyzed",
    "status.generated": "Ads Generated",
    "status.simulated": "Simulated",
    "status.completed": "Completed",

    "flow.step1": "Describe the Product",
    "flow.step2": "Strategic Interpretation",
    "flow.step3": "Ad Variations",
    "flow.step4": "Audience Simulation",
    "flow.step5": "Final Result",
    "flow.step1_desc": "Fill in the product data to start the analysis.",
    "flow.step2_desc": "The system strategically interpreted your product.",
    "flow.step3_desc": "3 ad variations were automatically generated.",
    "flow.step4_desc": "4 simulated audience profiles reacted to the ads.",
    "flow.step5_desc": "The decision engine chose the best ad.",
    "flow.back": "Back",
    "flow.quick": "Quick",
    "flow.complete": "Complete",
    "flow.fill_example": "Fill example",
    "flow.product_name": "Product Name",
    "flow.niche": "Niche",
    "flow.main_promise": "Main Promise",
    "flow.audience": "Target Audience",
    "flow.benefits": "Benefits",
    "flow.mechanism": "Ingredients / Mechanism",
    "flow.tone": "Desired Tone",
    "flow.optional": "(optional)",
    "flow.compliance_risk": "Block risk detected",
    "flow.compliance_safe": "Avoid absolute medical claims. The system will flag block risk.",
    "flow.time_estimate": "Takes ~45s for full analysis",
    "flow.submit": "Find the best ad",
    "flow.generate_ads": "Choose the winning ad",
    "flow.run_simulation": "Run simulation",
    "flow.run_decision": "Run decision engine",
    "flow.refine": "Refine product data",
    "flow.refine_desc": "Add benefits, mechanism and tone for more precise results",
    "flow.additional_data": "Additional Data",
    "flow.close": "Close",
    "flow.example_filled": "Example filled!",
    "flow.error_create": "Error creating analysis",
    "flow.error_generate": "Error generating ads",
    "flow.error_simulate": "Error simulating audience",
    "flow.error_decide": "Error processing decision",

    "strategy.title": "Strategic Interpretation",
    "strategy.consciousness": "Consciousness Level",
    "strategy.angle": "Sales Angle",
    "strategy.pain": "Core Pain",
    "strategy.big_idea": "Big Idea",
    "strategy.mechanism": "Perceived Mechanism",
    "strategy.objections": "Likely Objections",
    "strategy.compliance_score": "Compliance Score",

    "ads.experiment": "Click Experiment",
    "ads.hypothesis": "Hypothesis",
    "ads.works_for": "Works best for",
    "ads.hook": "Hook",
    "ads.copy": "Copy",
    "ads.ugc_script": "UGC Script",
    "ads.strengths": "Strengths",
    "ads.weaknesses": "Weaknesses",
    "ads.ctr": "Est. CTR",
    "ads.curiosity": "Curiosity",
    "ads.block_risk": "Block Risk",
    "ads.conversion": "Conversion",
    "ads.experimental_note": "We don't evaluate ads by aesthetics, but by likely audience reaction.",

    "sim.ad_num": "Ad",
    "sim.first_reaction": "1st reaction",
    "sim.after_2s": "After 2s",
    "sim.would_click": "Would click if",
    "sim.trend": "General trend",
    "sim.conflict": "Conflict",

    "dec.verdict": "Decision Engine Verdict",
    "dec.chosen": "Chosen Ad: Variation",
    "dec.score": "Score",
    "dec.wrong_choice": "Consequence of wrong choice",
    "dec.use_now": "This is the ad you should use now",
    "dec.investment": "If investing $500",
    "dec.next_step": "Recommended next step",
    "dec.reason": "Reason",
    "dec.weaknesses_detected": "Weaknesses detected",
    "dec.improvement_suggestion": "Improvement suggestion",
    "dec.lp_structure": "Suggested LP structure",
    "dec.compatible_audience": "Most compatible audience",
    "dec.ranking": "Ranking",
    "dec.loop_msg": "The system will keep learning if you generate new versions.",
    "dec.use_ad": "Use this ad",
    "dec.improve": "Improve ad",
    "dec.new_variation": "Test new variation",
    "dec.next_tests": "Recommended next tests",
    "dec.copied": "Copied!",
    "dec.share_copied": "Public link copied!",
    "dec.share_error": "Error generating link",
    "dec.improve_error": "Error creating improvement",

    "comp.title": "Analyze Competitor",
    "comp.headline": "Decode the strategy",
    "comp.desc": "Paste the URL of a competitor's ad or landing page.",
    "comp.analyze": "Analyze",
    "comp.extraction": "Strategic Extraction",
    "comp.opening_type": "Opening Type",
    "comp.promise": "Promise",
    "comp.mechanism": "Mechanism",
    "comp.proof": "Proof",
    "comp.cta": "CTA",
    "comp.psychology": "Psychology",
    "comp.visual_format": "Visual Format",
    "comp.block_risk": "Block Risk",
    "comp.what_it_does": "What the ad tries to do",
    "comp.why_works": "Why it might work",
    "comp.where_weak": "Where it loses strength",
    "comp.how_beat": "How to beat it",
    "comp.keywords": "Keywords",
    "comp.ctas_found": "CTAs found",
    "comp.create_superior": "CREATE SUPERIOR VERSION",
    "comp.history": "Previous analyses",
    "comp.show": "Show",
    "comp.hide": "Hide",
    "comp.done": "Analysis complete!",
    "comp.error": "Error analyzing URL",

    "mkt.title": "Compare with Market",
    "mkt.desc_prefix": "See how the market sells in the niche",
    "mkt.desc_suffix": "and where you have an advantage.",
    "mkt.scan_info": "The engine will analyze how the market sells in the niche",
    "mkt.scan_detail": "It will identify dominant patterns, persistent ads and compare with your strategy.",
    "mkt.scan": "Scan market",
    "mkt.rescan": "Scan again",
    "mkt.hooks": "Market Hook Distribution",
    "mkt.patterns": "Dominant Patterns",
    "mkt.persistent": "Persistent Ads",
    "mkt.examples": "Market Examples",
    "mkt.persistence": "Persistence",
    "mkt.vs_market": "Your Strategy vs Market",
    "mkt.how_market": "How the market sells",
    "mkt.where_differ": "Where you differ",
    "mkt.advantage": "Your Competitive Advantage",
    "mkt.generic_risk": "Risk of looking generic",
    "mkt.recommendation": "Practical Recommendation",
    "mkt.generate_creative": "GENERATE CREATIVE BASED ON ADVANTAGE",
    "mkt.done": "Comparison complete!",
    "mkt.error": "Error comparing with market",

    "step.product": "Product",
    "step.strategy": "Strategy",
    "step.ads": "Ads",
    "step.simulation": "Simulation",
    "step.decision": "Decision",

    "hook.pergunta": "Question",
    "hook.historia": "Story",
    "hook.lista": "List",
    "hook.prova_social": "Social Proof",
    "hook.mecanismo": "Mechanism",
    "hook.choque": "Shock",
  },

  es: {
    "login.subtitle": "Motor de Decisión",
    "login.name": "Nombre",
    "login.name_placeholder": "Tu nombre",
    "login.email": "Email",
    "login.password": "Contraseña",
    "login.submit_register": "Crear Cuenta",
    "login.submit_login": "Entrar",
    "login.toggle_register": "¿No tienes cuenta? Crear",
    "login.toggle_login": "¿Ya tienes cuenta? Entrar",
    "login.success_register": "¡Cuenta creada!",
    "login.success_login": "¡Bienvenido de vuelta!",
    "login.error": "Error de autenticación",

    "dash.title": "Tus Análisis",
    "dash.subtitle": "Motor de decisión para anuncios",
    "dash.new_analysis": "Nuevo Análisis",
    "dash.first_analysis": "Crear Primer Análisis",
    "dash.empty_question": "¿Qué decisión necesitas tomar hoy?",
    "dash.empty_desc": "Describe tu producto y deja que el motor decida el mejor anuncio.",
    "dash.history": "Historial",
    "dash.new_product": "+ Nuevo producto",
    "dash.deleted": "Análisis eliminado",
    "dash.delete_error": "Error al eliminar",
    "dash.open": "Abrir",
    "dash.delete": "Eliminar",
    "dash.logout": "Salir",
    "dash.versions_generated": "versiones generadas",

    "panel.active_product": "Producto Activo",
    "panel.product": "Producto",
    "panel.current_strategy": "Estrategia Actual",
    "panel.biggest_weakness": "Mayor Debilidad",
    "panel.next_action": "Próxima Acción Recomendada",
    "panel.improve_ad": "Mejorar anuncio",
    "panel.compare_market": "Comparar con mercado",
    "panel.analyze_competitor": "Analizar competidor",

    "radar.title": "Radar de Tendencias",
    "radar.subtitle": "Briefing semanal del nicho",
    "radar.generate": "Generar Radar",
    "radar.generating": "Generando radar...",
    "radar.empty": "Genera un radar para ver tendencias de tu nicho",
    "radar.last_update": "Última actualización",
    "radar.changes": "Cambios en el Mercado",
    "radar.patterns": "Patrones Emergentes",
    "radar.recommendations": "Recomendaciones",
    "radar.summary": "Resumen",

    "status.created": "Creado",
    "status.parsed": "Analizado",
    "status.generated": "Anuncios Generados",
    "status.simulated": "Simulado",
    "status.completed": "Completado",

    "flow.step1": "Describe el Producto",
    "flow.step2": "Interpretación Estratégica",
    "flow.step3": "Variaciones de Anuncios",
    "flow.step4": "Simulación de Público",
    "flow.step5": "Resultado Final",
    "flow.step1_desc": "Completa los datos del producto para iniciar el análisis.",
    "flow.step2_desc": "El sistema interpretó estratégicamente tu producto.",
    "flow.step3_desc": "3 variaciones de anuncios fueron generadas automáticamente.",
    "flow.step4_desc": "4 perfiles de público simulados reaccionaron a los anuncios.",
    "flow.step5_desc": "El motor de decisión eligió el mejor anuncio.",
    "flow.back": "Volver",
    "flow.quick": "Rápido",
    "flow.complete": "Completo",
    "flow.fill_example": "Llenar ejemplo",
    "flow.product_name": "Nombre del Producto",
    "flow.niche": "Nicho",
    "flow.main_promise": "Promesa Principal",
    "flow.audience": "Público Objetivo",
    "flow.benefits": "Beneficios",
    "flow.mechanism": "Ingredientes / Mecanismo",
    "flow.tone": "Tono Deseado",
    "flow.optional": "(opcional)",
    "flow.compliance_risk": "Riesgo de bloqueo detectado",
    "flow.compliance_safe": "Evita promesas médicas absolutas. El sistema señalará riesgo de bloqueo.",
    "flow.time_estimate": "Toma ~45s para análisis completo",
    "flow.submit": "Encontrar el mejor anuncio",
    "flow.generate_ads": "Elegir el anuncio ganador",
    "flow.run_simulation": "Ejecutar simulación",
    "flow.run_decision": "Ejecutar motor de decisión",
    "flow.refine": "Refinar datos del producto",
    "flow.refine_desc": "Agrega beneficios, mecanismo y tono para resultados más precisos",
    "flow.additional_data": "Datos Adicionales",
    "flow.close": "Cerrar",
    "flow.example_filled": "¡Ejemplo completado!",
    "flow.error_create": "Error al crear análisis",
    "flow.error_generate": "Error al generar anuncios",
    "flow.error_simulate": "Error al simular público",
    "flow.error_decide": "Error al procesar decisión",

    "strategy.title": "Interpretación Estratégica",
    "strategy.consciousness": "Nivel de Conciencia",
    "strategy.angle": "Ángulo de Venta",
    "strategy.pain": "Dolor Central",
    "strategy.big_idea": "Gran Idea",
    "strategy.mechanism": "Mecanismo Percibido",
    "strategy.objections": "Objeciones Probables",
    "strategy.compliance_score": "Puntuación de Compliance",

    "ads.experiment": "Experimento de Clic",
    "ads.hypothesis": "Hipótesis",
    "ads.works_for": "Funciona mejor para",
    "ads.hook": "Hook",
    "ads.copy": "Copy",
    "ads.ugc_script": "Guión UGC",
    "ads.strengths": "Fortalezas",
    "ads.weaknesses": "Debilidades",
    "ads.ctr": "CTR Est.",
    "ads.curiosity": "Curiosidad",
    "ads.block_risk": "Riesgo Bloqueo",
    "ads.conversion": "Conversión",
    "ads.experimental_note": "No evaluamos anuncios por estética, sino por reacción probable del público.",

    "sim.ad_num": "Anuncio",
    "sim.first_reaction": "1ª reacción",
    "sim.after_2s": "Después de 2s",
    "sim.would_click": "Haría clic si",
    "sim.trend": "Tendencia general",
    "sim.conflict": "Conflicto",

    "dec.verdict": "Veredicto del Motor de Decisión",
    "dec.chosen": "Anuncio Elegido: Variación",
    "dec.score": "Puntuación",
    "dec.wrong_choice": "Consecuencia de elegir mal",
    "dec.use_now": "Este es el anuncio que debes usar ahora",
    "dec.investment": "Si estuvieras invirtiendo $500",
    "dec.next_step": "Próximo paso recomendado",
    "dec.reason": "Motivo",
    "dec.weaknesses_detected": "Debilidades detectadas",
    "dec.improvement_suggestion": "Sugerencia de mejora",
    "dec.lp_structure": "Estructura de LP sugerida",
    "dec.compatible_audience": "Público más compatible",
    "dec.ranking": "Ranking",
    "dec.loop_msg": "El sistema seguirá aprendiendo si generas nuevas versiones.",
    "dec.use_ad": "Usar este anuncio",
    "dec.improve": "Mejorar anuncio",
    "dec.new_variation": "Probar nueva variación",
    "dec.next_tests": "Próximas pruebas recomendadas",
    "dec.copied": "¡Copiado!",
    "dec.share_copied": "¡Enlace público copiado!",
    "dec.share_error": "Error al generar enlace",
    "dec.improve_error": "Error al crear mejora",

    "comp.title": "Analizar Competidor",
    "comp.headline": "Decodifica la estrategia",
    "comp.desc": "Pega la URL de un anuncio o landing page del competidor.",
    "comp.analyze": "Analizar",
    "comp.extraction": "Extracción Estratégica",
    "comp.opening_type": "Tipo de Apertura",
    "comp.promise": "Promesa",
    "comp.mechanism": "Mecanismo",
    "comp.proof": "Prueba",
    "comp.cta": "CTA",
    "comp.psychology": "Psicología",
    "comp.visual_format": "Formato Visual",
    "comp.block_risk": "Riesgo de Bloqueo",
    "comp.what_it_does": "Lo que el anuncio intenta hacer",
    "comp.why_works": "Por qué puede funcionar",
    "comp.where_weak": "Donde pierde fuerza",
    "comp.how_beat": "Cómo superarlo",
    "comp.keywords": "Palabras clave",
    "comp.ctas_found": "CTAs encontrados",
    "comp.create_superior": "CREAR VERSIÓN SUPERIOR",
    "comp.history": "Análisis anteriores",
    "comp.show": "Mostrar",
    "comp.hide": "Ocultar",
    "comp.done": "¡Análisis completo!",
    "comp.error": "Error al analizar URL",

    "mkt.title": "Comparar con Mercado",
    "mkt.desc_prefix": "Mira cómo el mercado vende en el nicho",
    "mkt.desc_suffix": "y dónde tienes ventaja.",
    "mkt.scan_info": "El motor analizará cómo el mercado vende en el nicho",
    "mkt.scan_detail": "Identificará patrones dominantes, anuncios persistentes y comparará con tu estrategia.",
    "mkt.scan": "Escanear mercado",
    "mkt.rescan": "Escanear de nuevo",
    "mkt.hooks": "Distribución de Hooks en el Mercado",
    "mkt.patterns": "Patrones Dominantes",
    "mkt.persistent": "Anuncios Persistentes",
    "mkt.examples": "Ejemplos del Mercado",
    "mkt.persistence": "Persistencia",
    "mkt.vs_market": "Tu Estrategia vs Mercado",
    "mkt.how_market": "Cómo vende el mercado",
    "mkt.where_differ": "Dónde te diferencias",
    "mkt.advantage": "Tu Ventaja Competitiva",
    "mkt.generic_risk": "Riesgo de parecer genérico",
    "mkt.recommendation": "Recomendación Práctica",
    "mkt.generate_creative": "GENERAR CREATIVO BASADO EN LA VENTAJA",
    "mkt.done": "¡Comparación completada!",
    "mkt.error": "Error al comparar con mercado",

    "step.product": "Producto",
    "step.strategy": "Estrategia",
    "step.ads": "Anuncios",
    "step.simulation": "Simulación",
    "step.decision": "Decisión",

    "hook.pergunta": "Pregunta",
    "hook.historia": "Historia",
    "hook.lista": "Lista",
    "hook.prova_social": "Prueba Social",
    "hook.mecanismo": "Mecanismo",
    "hook.choque": "Shock",
  },
};

const LANG_NAMES = { pt: "PT", en: "EN", es: "ES" };

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => localStorage.getItem("adop_lang") || "pt");

  const changeLang = useCallback((newLang) => {
    setLang(newLang);
    localStorage.setItem("adop_lang", newLang);
  }, []);

  const t = useCallback((key) => {
    return translations[lang]?.[key] || translations.pt[key] || key;
  }, [lang]);

  return (
    <LanguageContext.Provider value={{ lang, changeLang, t, LANG_NAMES }}>
      {children}
    </LanguageContext.Provider>
  );
};
